GET http://localhost:3000/todos

###
POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "Do Homework",
    "completed": false
}

###
PUT http://localhost:3000/todo/1
Content-Type: application/json

{
    "title": "Do Homework",
    "completed": true
}

###
DELETE http://localhost:3000/todo/1
